version: '3'

services:
  # 웹 서버
  web:
    container_name: earned-it
    build:
      context: . # build를 실행할 위치
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod

    depends_on:
      - redis

    networks:
      - backend

  # Redis 서버
  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "12341234" ]
    networks:
      - backend

networks:
  backend:



