# 실행법 !!
# 1. 루트 디렉토리에서 docker compose up -d 실행
# 2. Docker 앱 구동 또는 docker images 입력
# 3.


version: '3'

services:
  # postgres DB 이미지
  database:
    image: postgres
    container_name: postgresDB
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: earnedit
      POSTGRES_USER: root
      POSTGRES_PASSWORD: earnedit99

#    volumes:
#      - ./resources/init.sql # DB 초기화 시 사용


  # 웹 서버
  web:
    container_name: earned-it
    build:
      context: . # build를 실행할 위치
      dockerfile: Dockerfile
    ports:
      - "8080:8080"




