spring:
  application:
    name: earnedit

  datasource:
    url: jdbc:postgresql://${RDS_DB_URL}:5432/earnedit
    username: ${RDS_DB_USER}
    password: ${RDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  #메일 의존성
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
email:
  verification:
    url: http://localhost:8080/api/auth/email/verify