spring:
  datasource:
    url: jdbc:postgresql://${RDS_DB_URL}:5432/earnedit
    username: ${RDS_DB_USER}
    password: ${RDS_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # Redis
  data:
    redis:
      repositories:
        enabled: false
    elasticsearch:
      repositories:
        enabled: false

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}

# application-prod.yaml
logging:
  level:
    root: INFO